name: scavenger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true

  assets:
  - assets/pft_first_floor.png
  - assets/pft_second_floor.png
  - assets/pft_third_floor.png
  - assets/lsu_logo.png
  - assets/fonts/

  fonts:
    - family: Proxima Nova
      fonts:
      - asset: assets\fonts\proximanova_regular.ttf
      - asset: assets\fonts\proximanova_black.ttf
        weight: 700

